### ISSUE TITLE
Please add support for IdentityServer3 2.0.0-rc1

### ISSUE THREAD

**Issue by ma3yta** [imperugo/IdentityServer3.Contrib.Cache.Redis#4]
Please add support for [IdentityServer3 2.0.0-rc1](https://www.nuget.org/packages/IdentityServer3/2.0.0-rc1)

**Comment by imperugo** [comment]
Hi,
I'm adding the support for the V2 (now is on RTM)

**Comment by imperugo** [comment]
Started
