### ISSUE TITLE
IdentityServer3.Contrib.Cache.Redis

### ISSUE THREAD

**Issue by lmartinez0710** [imperugo/IdentityServer3.Contrib.Cache.Redis#6]

**Comment by lmartinez0710** [comment]
can someone help me?

**Comment by imperugo** [comment]
Hi @lmartinez0710 

you have to use like this

``` csharp

//Client cache provider
factory.ConfigureClientStoreCache(new Registration<ICache<Client>>(new ClientStoreCache(yourMultiplexInstance)));

//Scope cache provider
factory.ConfigureScopeStoreCache(new Registration<ICache<IEnumerable<Scope>>>(new ScopeStoreCache(yourMultiplexInstance)));

//User cache provider
factory.ConfigureUserServiceCache(new Registration<ICache<IEnumerable<Claim>>>(new UserServiceCache(yourMultiplexInstance)));
```

Thanks

**Comment by lmartinez0710** [comment]
Not working, here is my code.

**Comment by lmartinez0710** [comment]
var factory = new IdentityServerServiceFactory();

                        var clientStoreCache = new ClientStoreCache(RedisMultiplex);
                        var scopeStoreCache = new ScopeStoreCache(RedisMultiplex);
                        var userServiceCache = new UserServiceCache(RedisMultiplex);

                        InMemoryClientStore clientStore = new InMemoryClientStore(Clients.Get());
                        InMemoryScopeStore scopeStore = new InMemoryScopeStore(Scopes.Get());
                        InMemoryUserService userStore = new InMemoryUserService(Users.Get());

                        factory.ClientStore = new Registration<IClientStore>(clientStore);
                        factory.ScopeStore = new Registration<IScopeStore>(scopeStore);
                        factory.UserService = new Registration<IUserService>(userStore);

                        factory.ConfigureClientStoreCache(new Registration<ICache<Client>>(new ClientStoreCache(RedisMultiplex)));
                        factory.ConfigureScopeStoreCache(new Registration<ICache<IEnumerable<Scope>>>(new ScopeStoreCache(RedisMultiplex)));
                        factory.ConfigureUserServiceCache(new Registration<ICache<IEnumerable<Claim>>>(new UserServiceCache(RedisMultiplex)));

**Comment by lmartinez0710** [comment]
No error found, but no data in my redis.

**Comment by lmartinez0710** [comment]
can someone help me?

**Comment by lmartinez0710** [comment]
any help?

**Comment by imperugo** [comment]
Can i close this?
